# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  schedule:
    - cron: '0 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
           python-version: '3.x'

      - name: Set TimeZone
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date

      # Runs a set of commands using the runners shell
      - name: Run test
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install requests
          pip install html2text
          pip install sqlalchemy
          pip install flask_sqlalchemy
          pip install parsel
          pip install pyyaml
          pip install flask_cors
          python hello.py
          echo test, and deploy your project.
      - name: commit mysec.db
        run: | 
          git config user.name hhackk
          git config user.email hack163com@163.com
          git add .
          git commit -m "mysec.db" || echo ok
          git push  || echo ok
          
      - uses: actions/checkout@v2
        with:
           ref: gh-pages
      - name: copy
        run: |
          cp /tmp/*articles.json data/
          git config user.name hhackk
          git config user.email hack163com@163.com
          git add .
          git commit -m "add data" || echo ok
          git push || echo ok
          
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:hhackk/caiyun.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:gcfgcf/caiyun.git
            
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: gcfgcf
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: gcfgcf/caiyun
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages            
       
